### ISSUE TITLE
`NoClassDefFoundError`

### ISSUE THREAD

**Issue by Ledmington** [unimined/JvmDowngrader#11]
Steps to reproduce:
```bash
git clone https://github.com/Ledmington/emu.git
cd emu
./gradlew readelf:fatjar
cp readelf/build/libs/emu-readelf.jar .
java21 -jar jvmdowngrader-0.8.4-all.jar -c 52 downgrade -t emu-readelf.jar output.jar
java8 -jar output.jar
```

The output is this:
```bash
Exception in thread "main" java.lang.NoClassDefFoundError: xyz/wagyourtail/jvmdg/j11/stub/java_base/J_N_F_Path
        at com.ledmington.readelf.Main.main(Main.java:266)
Caused by: java.lang.ClassNotFoundException: xyz.wagyourtail.jvmdg.j11.stub.java_base.J_N_F_Path
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 1 more
```

It seems that the error is [here](https://github.com/Ledmington/emu/blob/master/readelf/src/main/java/com/ledmington/readelf/Main.java#L266).

P.S.: I really like your work and want to use it in [this project of mine](https://github.com/Ledmington/emu), so I will create more issues as I go through this process.

**Comment by wagyourtail** [comment]
see pinned
