### ISSUE TITLE
Runtime.version() fails to execute on java 8.

### ISSUE THREAD

**Issue by Patbox** [unimined/JvmDowngrader#19]
```
java.lang.ExceptionInInitializerError
        at mrpack4server.xyz.wagyourtail.jvmdg.j9.stub.java_base.J_L_Runtime.version(J_L_Runtime.java:21)
        at eu.pb4.mrpackserver.launch.LegacyExitBlocker.run(LegacyExitBlocker.java:8)
        at eu.pb4.mrpackserver.Main.main(Main.java:63)
Caused by: java.lang.IllegalArgumentException: Invalid version string: '1.8.0_422-8u422-b05-1~22.04-b05'
        at mrpack4server.xyz.wagyourtail.jvmdg.j9.stub.java_base.J_L_Runtime$Version.parse(J_L_Runtime.java:54)
        at mrpack4server.xyz.wagyourtail.jvmdg.j9.stub.java_base.J_L_Runtime$Version.<clinit>(J_L_Runtime.java:26)
        ... 3 more
```

**Comment by Geolykt** [comment]
That uh, is a really peculiar version of java. Where does it come from?

**Comment by Patbox** [comment]
I'm pretty sure it's just regular distribution of openjdk 8 from ubuntu repo (as I'm developing this on Linux Mint).
```
patbox@PC:~$ /usr/lib/jvm/java-8-openjdk-amd64/bin/java -version
openjdk version "1.8.0_422"
OpenJDK Runtime Environment (build 1.8.0_422-8u422-b05-1~22.04-b05)
OpenJDK 64-Bit Server VM (build 25.422-b05, mixed mode)

```

**Comment by Fox2Code** [comment]
I made a fix, just need to wait for it to be merged
