### ISSUE TITLE
NoClassDefFoundError: xyz/wagyourtail/jvmdg/j16/stub/java_base/J_L_Record

### ISSUE THREAD

**Issue by andrew121410** [unimined/JvmDowngrader#7]
I downgraded one of our Minecraft Spigot plugins we use called ViaVersion because they bumped to Java 17 when i downgrade the JAR to Java 8 and then run the Spigot Minecraft Server I get this error. [https://mclo.gs/NFja0lN](https://mclo.gs/NFja0lN)

(Not sure If I did something wrong) 

I did do ` java -jar JvmDowngrader-all.jar -c 52 downgrade -t ViaVersionToDowngrade.jar ViaVersion.jar`

Raw:
`] [ERROR] Could not load 'plugins/ViaVersion.jar' in folder 'plugins'
[20.06 17:24:23] [Server] org.bukkit.plugin.InvalidPluginExceptionjava.lang.NoClassDefFoundError: xyz/wagyourtail/jvmdg/j16/stub/java_base/J_L_Record
[20.06 17:24:23] [Server] 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1620]
[20.06 17:24:23] [Server] 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1620]
[20.06 17:24:23] [Server] 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[patched_1.12.2.jar:git-Paper-1620]
[20.06 17:24:23] [Server] 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[patched_1.12.2.jar:git-Paper-1620]
[20.06 17:24:23] [Server] 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1620]
[20.06 17:24:23] [Server] 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
[20.06 17:24:23] [Server] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
[20.06 17:24:23] [Server] Caused byjava.lang.NoClassDefFoundError: xyz/wagyourtail/jvmdg/j16/stub/java_base/J_L_Record
[20.06 17:24:23] [Server] 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[patched_1.12.2.jar:git-Paper-1620]
[20.06 17:24:23] [Server] 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1620]
[20.06 17:24:23] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at com.viaversion.viaversion.protocol.ProtocolManagerImpl.<init>(ProtocolManagerImpl.java:126) ~[?:?]
[20.06 17:24:23] [Server] 	at com.viaversion.viaversion.ViaManagerImpl.<init>(ViaManagerImpl.java:58) ~[?:?]
[20.06 17:24:23] [Server] 	at com.viaversion.viaversion.ViaManagerImpl$ViaManagerBuilder.build(ViaManagerImpl.java:370) ~[?:?]
[20.06 17:24:23] [Server] 	at com.viaversion.viaversion.ViaVersionPlugin.<init>(ViaVersionPlugin.java:73) ~[?:?]
[20.06 17:24:23] [Server] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:94) ~[patched_1.12.2.jar:git-Paper-1620]
[20.06 17:24:23] [Server] 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1620]
[20.06 17:24:23] [Server] 	... more
[20.06 17:24:23] [Server] Caused byjava.lang.ClassNotFoundException: xyz.wagyourtail.jvmdg.j16.stub.java_base.J_L_Record
[20.06 17:24:23] [Server] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[patched_1.12.2.jar:git-Paper-1620]
[20.06 17:24:23] [Server] 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1620]
[20.06 17:24:23] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[patched_1.12.2.jar:git-Paper-1620]
[20.06 17:24:23] [Server] 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1620]
[20.06 17:24:23] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at com.viaversion.viaversion.protocol.ProtocolManagerImpl.<init>(ProtocolManagerImpl.java:126) ~[?:?]
[20.06 17:24:23] [Server] 	at com.viaversion.viaversion.ViaManagerImpl.<init>(ViaManagerImpl.java:58) ~[?:?]
[20.06 17:24:23] [Server] 	at com.viaversion.viaversion.ViaManagerImpl$ViaManagerBuilder.build(ViaManagerImpl.java:370) ~[?:?]
[20.06 17:24:23] [Server] 	at com.viaversion.viaversion.ViaVersionPlugin.<init>(ViaVersionPlugin.java:73) ~[?:?]
[20.06 17:24:23] [Server] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_311]
[20.06 17:24:23] [Server] 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:94) ~[patched_1.12.2.jar:git-Paper-1620]
[20.06 17:24:23] [Server] 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1620]
[20.06 17:24:23] [Server] 	... more`

**Comment by Geolykt** [comment]
Potential duplicate of #4 

RTFM?

**Comment by wagyourtail** [comment]
looks like it to me

**Comment by andrew121410** [comment]
Ohhh ok yeah I'm dumb, now I get what the shading does in the README.md
